services:
  - type: web
    name: dse-stock-price-prediction
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_ONLY_BINARY
        value: ":all:"
    buildCommand: pip install -r requirements.txt && python -m backend.app.training.train
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
